fixed the matching bugs
vhive-serverless/scholar-scout pull request #1
Opened 2024-12-25 11:08 UTC by JasonZhang517

2025-01-03 09:25 UTC, JasonZhang517 commented on requirements-dev.txt
> +# Code style and linting
one is for the tool itself, one is for linting and testing

2025-01-06 02:34 UTC, JasonZhang517 commented on tests/test_scholar_classifier.py
> +            expected_channels = ["#systems-for-ai", "#serverless-systems"]
no this is the expect channels, namely for checking the results

2025-01-13 06:07 UTC, ustiugov submitted a review, later dismissed
- [x] make sure there is no code duplication. This is the third time I note it down
- [ ] refactor long functions if they don't fit into a single screen, use helper functions. the lonely exception is for test functions, which are clear to read

2025-01-13 06:07 UTC, ustiugov commented on scholar_classifier.py
>  class Paper:
this class is defined in `paper.py`

2025-01-13 06:07 UTC, ustiugov commented on scholar_classifier.py
>                  paper = {
should initialized via the Paper class

2025-01-20 09:11 UTC, JasonZhang517 commented
Since Dmitrii is currently not here, can you help to review the repo to also make this repo as a role model for maintaining github repos?
@leokondrashov

2025-01-21 08:24 UTC, leokondrashov commented on scholar_classifier.py
> +            last_update_file = ".last_weekly_update"
No one writes to this file except tests. And tests remove it after themselves (including the one generated before them). Are you sure that's a good way to remember?

2025-01-21 08:24 UTC, leokondrashov commented on tests/test_gmail_connection.py
> +                results = self.classifier.extract_and_classify_papers(email_message)
You are doing the gmail test, why do you classify them?

2025-01-21 08:24 UTC, leokondrashov commented on tests/test_integration.py
>  class TestGmailIntegration(unittest.TestCase):
Why is it called Gmail integration? We have separate test for gmail connections, this one should be just integration, right?

2025-01-21 08:24 UTC, leokondrashov commented on tests/test_integration.py
>      def test_end_to_end_pipeline(self):
How close is this test to scholar classifier's run()? If you change the logic there, you would need to update it here to make a proper test. Can you run the main logic and only check the results here?

2025-01-21 08:24 UTC, leokondrashov commented on tests/test_slack_notifier.py
> +            required_vars = ["GMAIL_USERNAME", "GMAIL_APP_PASSWORD", "PPLX_API_KEY"]
Why do you need all of them but not the slack token?

2025-01-22 08:13 UTC, JasonZhang517 commented on README.md
> +- The tests expect Google Scholar alert emails from January 5th, 2025 in the specified folder
We are using some valid paper to test the system. The situation is that if there is not a valid paper of certain date in the inbox, the test will fail. I think we just maintain it, it is just for tests

2025-01-22 08:14 UTC, JasonZhang517 commented on tests/test_integration.py
> +            folder = "Inbox"
I just changed it last week, currently there is no valid email in the label.
Will change it later.

2025-01-22 08:27 UTC, JasonZhang517 commented on config.py
> +class Paper:
because all the class definitions are there.

2025-01-22 08:28 UTC, JasonZhang517 commented on scholar_classifier.py
> +        with open("search_criteria.yml", "r") as f:
so the initial thought by Dmitrii is upload .yaml and user will convert to .yml file

2025-01-23 03:27 UTC, leokondrashov commented on scholar_classifier.py
> +        with open("search_criteria.yml", "r") as f:
I'd propose more explicit name for source, like `.example.yaml` or similar. Also, I don't see instructions about that in the docs, did I miss them?

2025-01-24 12:03 UTC, ustiugov requested changes
please fix the remaining, they are not captured by the Issues you created

2025-01-24 12:03 UTC, ustiugov commented on tests/test_integration.py
> +            folder = "Inbox"
no, copy the emails, and change it now

2025-01-24 12:03 UTC, ustiugov commented on scholar_classifier.py
> +        with open("search_criteria.yml", "r") as f:
I agree, need to do

2025-01-24 12:03 UTC, ustiugov commented on scholar_classifier.py
> +            last_update_file = ".last_weekly_update"
definite not a good way

2025-01-24 12:03 UTC, ustiugov commented on scholar_classifier.py
> +                slack_channel=topic_config.get("slack_channel"),
agreed, please do

2025-01-24 12:03 UTC, ustiugov commented on scholar_classifier.py
> +    def _create_topic(self, topic_dict):
agreed, remove duplicate

2025-01-24 16:04 UTC, ustiugov requested changes

2025-01-24 16:04 UTC, ustiugov commented on search_criteria.example.yaml
> +email_filter:
Why is this one YAML and the other one yml? Just use one everywhere

2025-01-24 16:04 UTC, ustiugov commented on scholar_classifier.py
> +        with open("search_criteria.yml", "r") as f:
Still not done with yaml and yml

2025-01-26 08:46 UTC, ustiugov commented on .github/workflows/scholar_classifier.yml
> +        cp config.yaml config.yml
What is this yaml yml?

2025-01-30 08:07 UTC, ustiugov approved these changes

2025-01-30 08:35 UTC, merged